# Generated by Django 4.2.16 on 2024-12-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.JSONField(default=dict, verbose_name='Country name'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='info',
            field=models.JSONField(default=dict, verbose_name='Additional info'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.JSONField(default=dict, verbose_name='Hotel name'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nutrition',
            field=models.JSONField(default=dict, verbose_name='Nutrition info'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.JSONField(default=dict, verbose_name='Tour names'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='photo_url',
            field=models.CharField(default='https://media.worldnomads.com/Explore/middle-east/hagia-sophia-church-istanbul-turkey-gettyimages-skaman306.jpg', max_length=255, verbose_name='photo_url'),
        ),
    ]
