# Generated by Django 4.2.16 on 2024-12-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_country_name_alter_hotel_info_alter_hotel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Country name'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='info',
            field=models.TextField(verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Hotel name'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nutrition',
            field=models.TextField(verbose_name='Nutrition'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tour name'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='photo_url',
            field=models.CharField(default='https://media.worldnomads.com/Explore/middle-east/hagia-sophia-church-istanbul-turkey-gettyimages-skaman306.jpg', max_length=200, verbose_name='photo_url'),
        ),
    ]
