# Generated by Django 4.2.16 on 2024-12-14 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.IntegerField(),
        ),
    ]
